- params:
    git:
      repoName: jfrog-awsfloor28-security
      branches:
        - main
    scan:
      projects:
        - workingDirs:
            - ./Source
    includeAllVulnerabilities: true
